/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.phoshoko.app;

import com.phoshoko.storage.Connect;
import com.phoshoko.storage.Users;
import com.phoshoko.utilities.Logic;
import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 *
 * @author Mpho
 */
public class Authentication extends javax.swing.JFrame {

    //varibles
    private static App app = new App();
    private static Users client;
    public static boolean validUser = false, animationLblUsername = true, animationPasLogin = true;
    private int xMouse;
    private int yMouse;
    
    /**
     * Creates new form Authentication
     */
    public Authentication() {
        initComponents();
        
       
        lblWelcome.requestFocus();
        // Path to the image file, relative to the project root or source folder
        String imagePath = "/com/phoshoko/images/fern.png";

        try {
            // Use getClass().getResource() to get the URL of the resource
            // The leading '/' ensures the path is absolute from the classpath root
            ImageIcon icon = new ImageIcon(App.class.getResource(imagePath));

            // Set the JFrame's icon using the loaded image
            this.setIconImage(icon.getImage());
        
            
        } catch (Exception e) {
            System.err.println("Error: The image file was not found at " + imagePath);
            e.printStackTrace();
        }
    }
   

    public static Users getClient() {
        return client;
    }
    public static void setClient(Users clients) {
        client =clients;
    }
    public App getApp(){
        return app;
    }
    public void resetAuthLabels(){
        txfUsername.setText("");
        pasLogin.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlHeaderLogin = new javax.swing.JPanel();
        btnExitLogin = new javax.swing.JButton();
        btnMinimizeLogin = new javax.swing.JButton();
        pnlBackgroundWelcomeLogin = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        pnlWelcome = new javax.swing.JPanel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        lblWelcome = new javax.swing.JLabel();
        lblLine2 = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        lblLine3 = new javax.swing.JLabel();
        pasLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblValidation = new javax.swing.JLabel();
        lblWelcomeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FarmManenangementSystem");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlHeaderLogin.setBackground(new java.awt.Color(240, 235, 225));
        pnlHeaderLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        pnlHeaderLogin.setPreferredSize(new java.awt.Dimension(800, 30));
        pnlHeaderLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderLoginMouseDragged(evt);
            }
        });
        pnlHeaderLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderLoginMousePressed(evt);
            }
        });

        btnExitLogin.setBackground(new java.awt.Color(242, 242, 242));
        btnExitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/Exit.png"))); // NOI18N
        btnExitLogin.setBorder(null);
        btnExitLogin.setContentAreaFilled(false);
        btnExitLogin.setFocusable(false);
        btnExitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitLoginMouseExited(evt);
            }
        });
        btnExitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitLoginActionPerformed(evt);
            }
        });

        btnMinimizeLogin.setBackground(new java.awt.Color(242, 242, 242));
        btnMinimizeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/minus.png"))); // NOI18N
        btnMinimizeLogin.setBorder(null);
        btnMinimizeLogin.setContentAreaFilled(false);
        btnMinimizeLogin.setFocusable(false);
        btnMinimizeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizeLoginMouseExited(evt);
            }
        });
        btnMinimizeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLoginLayout = new javax.swing.GroupLayout(pnlHeaderLogin);
        pnlHeaderLogin.setLayout(pnlHeaderLoginLayout);
        pnlHeaderLoginLayout.setHorizontalGroup(
            pnlHeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitLogin)
                .addGap(0, 0, 0))
        );
        pnlHeaderLoginLayout.setVerticalGroup(
            pnlHeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMinimizeLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnExitLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlBackgroundWelcomeLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackgroundWelcomeLogin.setPreferredSize(new java.awt.Dimension(800, 570));

        pnlWelcome.setBackground(new java.awt.Color(204, 255, 255));
        pnlWelcome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        pnlWelcome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlWelcome.setPreferredSize(new java.awt.Dimension(400, 400));

        jLayeredPane5.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome");
        jLayeredPane5.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        lblLine2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblLine2.setPreferredSize(new java.awt.Dimension(350, 4));
        jLayeredPane5.add(lblLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txfUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txfUsername.setText("Username");
        txfUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        txfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfUsernameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txfUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txfUsernameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txfUsernameMousePressed(evt);
            }
        });
        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });
        jLayeredPane5.add(txfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 350, 40));

        lblLine3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblLine3.setPreferredSize(new java.awt.Dimension(350, 4));
        jLayeredPane5.add(lblLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        pasLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pasLogin.setText("adminpass");
        pasLogin.setBorder(txfUsername.getBorder());
        pasLogin.setMinimumSize(new java.awt.Dimension(71, 22));
        jLayeredPane5.add(pasLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 350, 40));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jLayeredPane5.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 40));

        lblValidation.setBackground(new java.awt.Color(255, 0, 0));
        lblValidation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValidation.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane5.add(lblValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 30));

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane5)
        );

        jLayeredPane4.add(pnlWelcome);
        pnlWelcome.setBounds(200, 110, 400, 370);

        lblWelcomeImage.setBackground(new java.awt.Color(0, 0, 0));
        lblWelcomeImage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/SignUpScreenBackground.jpg"))); // NOI18N
        lblWelcomeImage.setOpaque(true);
        jLayeredPane4.add(lblWelcomeImage);
        lblWelcomeImage.setBounds(0, -20, 800, 630);

        javax.swing.GroupLayout pnlBackgroundWelcomeLoginLayout = new javax.swing.GroupLayout(pnlBackgroundWelcomeLogin);
        pnlBackgroundWelcomeLogin.setLayout(pnlBackgroundWelcomeLoginLayout);
        pnlBackgroundWelcomeLoginLayout.setHorizontalGroup(
            pnlBackgroundWelcomeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        pnlBackgroundWelcomeLoginLayout.setVerticalGroup(
            pnlBackgroundWelcomeLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundWelcomeLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeaderLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackgroundWelcomeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeaderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBackgroundWelcomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitLoginMouseEntered
        btnExitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/ExitFilled.png")));
    }//GEN-LAST:event_btnExitLoginMouseEntered

    private void btnExitLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitLoginMouseExited
        btnExitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/Exit.png")));
    }//GEN-LAST:event_btnExitLoginMouseExited

    private void btnExitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitLoginActionPerformed

    private void btnMinimizeLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeLoginMouseEntered
        btnMinimizeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/minusBold.png")));
    }//GEN-LAST:event_btnMinimizeLoginMouseEntered

    private void btnMinimizeLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeLoginMouseExited
        btnMinimizeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/phoshoko/images/minus.png")));
    }//GEN-LAST:event_btnMinimizeLoginMouseExited

    private void btnMinimizeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeLoginActionPerformed
        this.setState(Frame.ICONIFIED);  // TODO add your handling code here:
    }//GEN-LAST:event_btnMinimizeLoginActionPerformed

    private void pnlHeaderLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderLoginMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderLoginMouseDragged

    private void pnlHeaderLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderLoginMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderLoginMousePressed
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!txfUsername.getText().isEmpty()||!pasLogin.getText().isEmpty()) {
            validUser = Logic.login(txfUsername.getText(), pasLogin.getText());
        if (validUser) {
            for (int i = 0; i < Connect.getSizeUsers(); i++) {
                if (Connect.getUsersList().get(i).getUsername().equals(txfUsername.getText())) {
                    client = Connect.getUsersList().get(i);
                }

            }
            app.setLblUsername(client.getUsername());
            this.setVisible(false);
        }

        if (validUser) {
            if (client.getRole().equalsIgnoreCase("admin")) {
                for (int i = 0; i < 14; i++) {
                    app.getAdminLabels()[i].setVisible(true);
                }

            } else {
                for (int i = 0; i < 14; i++) {
                    app.getAdminLabels()[i].setVisible(false);
                }
            }
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {

                    app.setVisible(true);

                }
            });
        }

        if (!validUser) {
            lblValidation.setText("username or password incorrect");
        }
        }else{
            lblValidation.setText("Fill in all the fields");
        }
        

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void txfUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfUsernameMousePressed

    }//GEN-LAST:event_txfUsernameMousePressed

    private void txfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfUsernameMouseClicked

    }//GEN-LAST:event_txfUsernameMouseClicked

    private void txfUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfUsernameMouseEntered

    }//GEN-LAST:event_txfUsernameMouseEntered

    private void txfUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfUsernameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameMouseExited
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
     
    }//GEN-LAST:event_formComponentShown

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMinimizeLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblLine3;
    private javax.swing.JLabel lblValidation;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcomeImage;
    private javax.swing.JPasswordField pasLogin;
    private javax.swing.JPanel pnlBackgroundWelcomeLogin;
    private javax.swing.JPanel pnlHeaderLogin;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
